### ISSUE TITLE
Auto-chunking of message parts

### ISSUE THREAD

**Issue by mverzilli** [manastech/cet-instagram#2]
1. Identify the maximum supported length.
2. If message exceeds the maximum, split it in parts (don't split lines).
3. Send all parts to the same user before moving to the next user (instead of sending the same part to all users before moving to the next part).
4. Extract links and send them in a standalone message so that it is easy for recipients to copy the link and paste it in their browser. You can assume all links will start with `http://` or `https://` and end in the next space.

**Comment by vtiffenberg** [comment]
1. Just managed to send 1000 characters
